import braintree from "braintree";

// PURPOSE:
// Submits the transaction to Braintree for processing after hitting "Pay"
// Receives a payment method nonce generated by the Drop-in UI

const gateway = new braintree.BraintreeGateway({
    environment: braintree.Environment.Sandbox,
    merchantId: process.env.BRAINTREE_MERCHANT_ID,
    publicKey: process.env.BRAINTREE_PUBLIC_KEY,
    privateKey: process.env.BRAINTREE_PRIVATE_KEY,
});

export async function handler(event) {
    const { paymentMethodNonce, amount } = JSON.parse(event.body);

    try {
        const result = await gateway.transaction.sale({
            amount: amount,
            paymentMethodNonce: paymentMethodNonce,
            options: { submitForSettlement: true },
        });

        return {
            statusCode: 200,
            body: JSON.stringify({ success: result.success, transaction: result.transaction }),
        };
    } catch (err) {
        return {
            statusCode: 500,
            body: JSON.stringify({ error: err.message }),
        };
    }
}
